name : "running unit test, build docker image, push ec2"
on :
  push:
    branches:
      - "development"
jobs :
  unit-test:
    name: "unit test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name : setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name : running unit-test
        run: go test ./... -cover
  build-push-docker:
    name : "build image and push registry to dockerhub"
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses : actions/checkout@v2
      - name : build image
        run : docker build -t agusdwimilniadi/investa_backend .
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ SECRETS.DOCKERHUB_USERNAME }}
          password: ${{ SECRETS.DOCKERHUB_PASSWORD }}
      - name: push image to dockerhub
        run: docker push agusdwimilniadi/investa_backend:latest
  deployment:
    name: "Deploy to ec2"
    runs-on: ubuntu-latest
    needs: build-push-docker
    steps:
      - uses: actions/checkout@v2
      - name : configuration ssh
        env:
          SSH_USER : ${{ SECRETS.SSH_USERNAME }}
          SSH_KEY: ${{ SECRETS.INVESTA_BACKEND_PEM }}
          SSH_HOST: ${{ SECRETS.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/InvestaBackend.pem
          chmod 700 ~/.ssh/InvestaBackend.pem
          cat >> ~/.ssh/config << END
          Host development
            Host_name : $SSH_HOST
            User : $SSH_USER
            IndentitiyFile ~/.ssh/InvestaBackend.pem
            StrictHostKeyCheking=no
          END
      - name: connect ec2, remove container, pull from registry and start
        run: ssh development 'docker rm -f $(docker ps -a -q)' || true && docker pull agusdwimilniadi/investa_backend:latest && docker run -d -p 8000:8000 --name inveta_backend agusdwimilniadi/investa_backend:latest
