// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	sektor "investaBackend/business/sektor"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// InsertSektor provides a mock function with given fields: domain, ctx
func (_m *Repository) InsertSektor(domain sektor.Domain, ctx context.Context) (sektor.Domain, error) {
	ret := _m.Called(domain, ctx)

	var r0 sektor.Domain
	if rf, ok := ret.Get(0).(func(sektor.Domain, context.Context) sektor.Domain); ok {
		r0 = rf(domain, ctx)
	} else {
		r0 = ret.Get(0).(sektor.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(sektor.Domain, context.Context) error); ok {
		r1 = rf(domain, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
